import { useMemo, useState } from "react";
import { Download, Eye, MoreVertical, Search, X } from "lucide-react";
import { DISEASES } from "../../../api";
import { Panel, RiskBadge, StatusBadge } from "./MedicalUi";

const formatDate = (v) => v ? new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(v)) : "—";
const formatTime = (v) => v ? new Intl.DateTimeFormat("en-IN", { hour: "2-digit", minute: "2-digit" }).format(new Date(v)) : "";

export default function DiseaseReports({ reports = [] }) {
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("All Status");
  const [disease, setDisease] = useState("All Diseases");
  const [taluk, setTaluk] = useState("All Taluks");
  const [selected, setSelected] = useState(null);
  const [page, setPage] = useState(1);
  const perPage = 6;
  const taluks = [...new Set(reports.map((r) => r.taluk_name).filter(Boolean))];

  const filtered = useMemo(() => reports.filter((r) => {
    const text = `${r.id} ${r.agent_name} ${r.disease} ${r.taluk_name}`.toLowerCase();
    const q = search.trim().toLowerCase();
    const statusOk = status === "All Status" || (r.status || "Pending Review").toLowerCase() === status.toLowerCase();
    return (!q || text.includes(q)) && (disease === "All Diseases" || r.disease === disease) && (taluk === "All Taluks" || r.taluk_name === taluk) && statusOk;
  }), [reports, search, status, disease, taluk]);
  const pageCount = Math.max(1, Math.ceil(filtered.length / perPage));
  const safePage = Math.min(page, pageCount);
  const visible = filtered.slice((safePage - 1) * perPage, safePage * perPage);

  const exportCsv = () => {
    const rows = filtered.map((r) => [r.id, r.disease, r.taluk_name, r.agent_name, r.cases, r.severity || "", formatDate(r.created_at)]);
    const csv = [["Report ID","Disease","Taluk","Agent","Cases","Severity","Submitted"], ...rows].map((row) => row.map((v) => `"${String(v ?? "").replaceAll('"','""')}"`).join(",")).join("\n");
    const blob = new Blob([csv], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = "kodagu-disease-reports.csv"; a.click(); URL.revokeObjectURL(url);
  };

  return <div className="space-y-5">
    <div className="rounded-2xl bg-[#087A32] px-5 py-4 text-white shadow-[0_6px_18px_rgba(8,122,50,.13)]"><div className="flex items-center justify-between gap-4"><div><div className="text-[14px] font-semibold">You are viewing: Kodagu District</div><div className="mt-1 text-[10px] text-white/80">Scoped to {taluks.length || 0} taluks and {new Set(reports.map((r) => r.agent_id)).size || 0} field agents reporting under your supervision</div></div><div className="hidden gap-8 text-right sm:flex"><div><b className="text-[19px]">{taluks.length}</b><div className="text-[9px] uppercase">Taluks</div></div><div><b className="text-[19px]">{new Set(reports.map((r) => r.agent_id)).size}</b><div className="text-[9px] uppercase">Agents</div></div><div><b className="text-[19px]">{reports.length}</b><div className="text-[9px] uppercase">Reports</div></div></div></div></div>
    <div className="flex items-center justify-between gap-3"><div><h1 className="text-[26px] font-semibold tracking-[-.03em]">Disease Reports</h1><p className="mt-1 text-[12px] text-[#66727D]">Case reports submitted by agents across Kodagu’s monitored taluks.</p></div><button type="button" onClick={exportCsv} className="inline-flex items-center gap-2 rounded-xl border border-[#DDE5E0] bg-white px-4 py-2.5 text-[11px] font-semibold"><Download size={15}/> Export</button></div>
    <Panel title="Report List">
      <div className="mb-4 grid gap-2.5 lg:grid-cols-[1.4fr_.75fr_.75fr_.75fr]"><label className="flex h-10 items-center gap-2 rounded-xl border border-[#DDE5E0] px-3"><Search size={16} className="text-[#758195]"/><input value={search} onChange={(e) => {setSearch(e.target.value);setPage(1)}} placeholder="Search reports, agents, diseases…" className="min-w-0 flex-1 bg-transparent text-[11px] outline-none"/></label><select value={status} onChange={(e) => setStatus(e.target.value)} className="rounded-xl border border-[#DDE5E0] bg-white px-3 text-[11px]"><option>All Status</option><option>Pending Review</option><option>Approved</option><option>Rejected</option></select><select value={disease} onChange={(e) => setDisease(e.target.value)} className="rounded-xl border border-[#DDE5E0] bg-white px-3 text-[11px]"><option>All Diseases</option>{DISEASES.map((d) => <option key={d}>{d}</option>)}</select><select value={taluk} onChange={(e) => setTaluk(e.target.value)} className="rounded-xl border border-[#DDE5E0] bg-white px-3 text-[11px]"><option>All Taluks</option>{taluks.map((t) => <option key={t}>{t}</option>)}</select></div>
      <div className="overflow-x-auto rounded-xl border border-[#E7ECE9]"><table className="w-full min-w-[930px] text-left text-[11px]"><thead className="bg-[#FAFBFA] text-[#768295]"><tr>{["REPORT ID","DISEASE","TALUK","AGENT","SUBMITTED","STATUS","PRIORITY","ACTIONS"].map((h) => <th key={h} className="px-3 py-3 text-[9px] font-bold tracking-[.04em]">{h}</th>)}</tr></thead><tbody>{visible.map((r) => { const priority = r.severity || (Number(r.cases) > 25 ? "High" : Number(r.cases) > 10 ? "Medium" : "Low"); const st = r.status || "Pending Review"; return <tr key={r.id} className="border-t border-[#EEF1EF] hover:bg-[#FBFDFB]"><td className="px-3 py-3 font-semibold text-[#25324A]">RPT-{String(r.id).padStart(4,"0")}</td><td className="px-3 py-3 font-semibold">{r.disease}</td><td className="px-3 py-3"><span className="rounded-md bg-[#F2F5F3] px-2 py-1">📍 {r.taluk_name}</span></td><td className="px-3 py-3">{r.agent_name}</td><td className="px-3 py-3"><div className="font-medium">{formatDate(r.created_at)}</div><div className="text-[9px] text-[#7C8795]">{formatTime(r.created_at)}</div></td><td className="px-3 py-3"><StatusBadge tone={st === "Approved" ? "green" : st === "Rejected" ? "red" : "blue"}>{st}</StatusBadge></td><td className="px-3 py-3"><RiskBadge level={priority === "Medium" ? "Moderate" : priority === "High" ? "High" : "Low"}/></td><td className="px-3 py-3"><div className="flex gap-1"><button onClick={() => setSelected(r)} className="flex h-8 w-8 items-center justify-center rounded-lg border border-[#DDE5E0] hover:bg-[#F5F8F6]"><Eye size={15}/></button><button onClick={() => setSelected(r)} className="flex h-8 w-8 items-center justify-center rounded-lg border border-[#DDE5E0] hover:bg-[#F5F8F6]"><MoreVertical size={15}/></button></div></td></tr>})}</tbody></table>{!visible.length && <div className="py-10 text-center text-[11px] text-[#718096]">No reports match the selected filters.</div>}</div>
      <div className="flex items-center justify-between pt-4 text-[10px] text-[#66727D]"><span>Showing {filtered.length ? (safePage - 1) * perPage + 1 : 0}–{Math.min(safePage * perPage, filtered.length)} of {filtered.length} reports</span><div className="flex gap-1"><button disabled={safePage <= 1} onClick={() => setPage((p) => Math.max(1,p-1))} className="h-8 w-8 rounded-lg border disabled:opacity-30">‹</button>{Array.from({length: pageCount}, (_, i) => i + 1).slice(Math.max(0,safePage-2), safePage+1).map((p) => <button key={p} onClick={() => setPage(p)} className={`h-8 min-w-8 rounded-lg border px-2 ${p===safePage ? "border-[#087A32] bg-[#087A32] text-white" : ""}`}>{p}</button>)}<button disabled={safePage >= pageCount} onClick={() => setPage((p) => Math.min(pageCount,p+1))} className="h-8 w-8 rounded-lg border disabled:opacity-30">›</button></div></div>
    </Panel>
    <div className="rounded-xl border border-[#DDEBE1] bg-[#F3FAF5] px-4 py-3 text-[11px] text-[#2D7047]"><b>Ensure Timely Review</b><span className="ml-2">Timely review of reports helps in early detection and quick response.</span></div>

    {selected && <div className="fixed inset-0 z-[70] flex items-center justify-center bg-[#102A43]/25 p-4" onMouseDown={() => setSelected(null)}><div onMouseDown={(e) => e.stopPropagation()} className="max-h-[85vh] w-full max-w-[620px] overflow-y-auto rounded-2xl bg-white shadow-2xl"><div className="flex items-start justify-between border-b p-5"><div><div className="text-[10px] font-bold uppercase tracking-[.1em] text-[#087A32]">Report Details</div><h3 className="mt-1 text-[20px] font-semibold">RPT-{String(selected.id).padStart(4,"0")}</h3></div><button onClick={() => setSelected(null)}><X size={19}/></button></div><div className="grid gap-4 p-5 sm:grid-cols-2">{[["Disease",selected.disease],["Taluk",selected.taluk_name],["Agent",selected.agent_name],["Cases",selected.cases],["Severity",selected.severity || "Not recorded"],["Submitted",`${formatDate(selected.created_at)} ${formatTime(selected.created_at)}`]].map(([k,v]) => <div key={k} className="rounded-xl bg-[#F7FAF8] p-3"><div className="text-[9px] font-bold uppercase tracking-[.08em] text-[#8A93A3]">{k}</div><div className="mt-1 text-[12px] font-semibold text-[#25324A]">{v}</div></div>)}</div><div className="px-5 pb-5"><div className="text-[11px] font-semibold">Remarks</div><p className="mt-2 rounded-xl border border-[#E7ECE9] p-3 text-[11px] leading-5 text-[#66727D]">{selected.remarks || "No remarks were submitted with this report."}</p><div className="mt-4 text-[11px] font-semibold">Preventive measures</div><p className="mt-2 rounded-xl border border-[#E7ECE9] p-3 text-[11px] leading-5 text-[#66727D]">{selected.preventive_measures || "No preventive measures were recorded."}</p></div></div></div>}
  </div>;
}
