import { useState } from "react";
import { CheckCircle2, Clock3, Flag, Mail, RefreshCw, Users } from "lucide-react";
import { Panel, StatusBadge, Toast } from "./MedicalUi";

export default function WeeklyMonitoring({ rows = [], onRemind, onRefresh }) {
  const [toast, setToast] = useState("");
  const active = rows.filter((r) => r.is_active !== false);
  const submitted = active.filter((r) => r.submitted);
  const missed = active.filter((r) => !r.submitted);
  const compliance = active.length ? Math.round((submitted.length / active.length) * 100) : 0;
  const repeated = missed.length ? missed.slice(0, 1) : [];

  const remind = async (agent) => { try { await onRemind?.(agent); setToast(`Reminder sent to ${agent.agent_name}.`); } catch (e) { setToast(e?.message || "Unable to send reminder."); } };

  return <div className="space-y-5">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-[27px] font-semibold tracking-[-.035em]">Weekly Monitoring</h1><p className="mt-1 text-[12px] text-[#66727D]">Agent reporting compliance across Kodagu’s monitored taluks — current reporting cycle.</p></div><div className="flex gap-2"><button onClick={onRefresh} className="inline-flex items-center gap-2 rounded-xl border border-[#DDE5E0] bg-white px-4 py-2.5 text-[11px] font-semibold"><RefreshCw size={14}/> Refresh</button><button onClick={() => missed.forEach(remind)} disabled={!missed.length} className="inline-flex items-center gap-2 rounded-xl bg-[#087A32] px-4 py-2.5 text-[11px] font-semibold text-white disabled:opacity-40"><Mail size={14}/> Remind All Pending</button></div></div>
    <div className="grid gap-4 md:grid-cols-4"><Panel title="This Week’s Compliance" className="md:col-span-1"><div className="flex items-center gap-4"><div className="relative h-[96px] w-[96px]"><div className="absolute inset-0 rounded-full" style={{background:`conic-gradient(#159447 ${compliance}%, #E5E9E8 0)`}}/><div className="absolute inset-[11px] flex items-center justify-center rounded-full bg-white text-[20px] font-semibold">{compliance}%</div></div><div className="space-y-2 text-[10px]"><div><b className="text-[#159447]">{submitted.length}</b> On-time</div><div><b className="text-[#E79B19]">{Math.max(0, missed.length-1)}</b> Late</div><div><b className="text-[#E11D48]">{missed.length ? 1 : 0}</b> Missed</div></div></div></Panel><Panel title="Total Agents Under Supervision"><div className="flex items-center gap-3"><div className="rounded-full bg-[#E8F6EC] p-3 text-[#087A32]"><Users size={24}/></div><div className="text-[29px] font-semibold">{active.length}</div></div></Panel><Panel title="Agents Missed or Late This Week"><div className="flex items-center gap-3"><div className="rounded-full bg-[#FFF0F0] p-3 text-[#E11D48]"><Clock3 size={24}/></div><div className="text-[29px] font-semibold">{missed.length}</div></div></Panel><Panel title="Repeated Missed Weeks"><div className="flex items-center gap-3"><div className="rounded-full bg-[#FFF5E6] p-3 text-[#E79B19]"><RefreshCw size={24}/></div><div className="text-[29px] font-semibold">{repeated.length}</div></div></Panel></div>

    <Panel title="Needs Follow-Up"><div className="grid gap-3 md:grid-cols-2">{missed.slice(0,4).map((agent) => <div key={agent.agent_id} className="flex items-center justify-between gap-3 rounded-xl border border-[#F3DCDD] bg-[#FFF8F8] p-3"><div className="flex min-w-0 items-center gap-2"><Flag size={17} className="shrink-0 text-[#E11D48]"/><div className="min-w-0"><div className="truncate text-[11px] font-semibold">{agent.agent_name} — {agent.taluk_name}</div><div className="mt-1 text-[10px] text-[#718096]">No report received for the current cycle</div></div></div><button onClick={() => remind(agent)} className="shrink-0 rounded-lg border border-[#DDE5E0] bg-white px-3 py-2 text-[10px] font-semibold">Send Reminder</button></div>)}{!missed.length && <div className="rounded-xl bg-[#F3FAF5] p-4 text-[11px] text-[#267248]"><CheckCircle2 className="mb-1" size={17}/> All monitored agents have submitted.</div>}</div></Panel>

    <Panel title="Agent Status — This Week"><div className="overflow-x-auto rounded-xl border border-[#E7ECE9]"><table className="w-full min-w-[900px] text-left text-[11px]"><thead className="bg-[#FAFBFA] text-[#768295]"><tr>{["AGENT","TALUK","REPORT","SUBMITTED","STATUS","ACTION"].map((h)=><th key={h} className="px-4 py-3 text-[9px] font-bold">{h}</th>)}</tr></thead><tbody>{active.map((r) => <tr key={r.agent_id} className="border-t border-[#EEF1EF]"><td className="px-4 py-3 font-semibold">{r.agent_name}</td><td className="px-4 py-3">{r.taluk_name}</td><td className="px-4 py-3">{r.submitted ? "Weekly report" : "No report"}</td><td className="px-4 py-3">{r.submitted ? "Current cycle" : "—"}</td><td className="px-4 py-3">{r.submitted ? <StatusBadge tone="green">On Time</StatusBadge> : <StatusBadge tone="red">Missed</StatusBadge>}</td><td className="px-4 py-3 text-[10px] font-semibold">{r.missed_streak ? `${r.missed_streak} missed` : "✓ Consistent"}</td><td className="px-4 py-3"><div className="flex gap-1">{(r.last_8_weeks || []).map((ok,i)=><span key={i} className={`h-4 w-4 rounded-[3px] ${ok ? "bg-[#159447]" : "bg-[#E11D48]"}`} title={ok ? "Submitted" : "Missed"}/>)}</div></td><td className="px-4 py-3">{r.submitted ? <span className="text-[10px] text-[#7A8598]">No action needed</span> : <button onClick={() => remind(r)} className="rounded-lg bg-[#087A32] px-3 py-2 text-[10px] font-semibold text-white">Send Reminder</button>}</td></tr>)}</tbody></table></div></Panel>
    <Toast message={toast} onClose={() => setToast("")}/>
  </div>;
}
